name: measure_size_example
description: An example app using the `measure_size` package

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  measure_size:
    path: ../
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3

dev_dependencies:
  pedantic: ^1.9.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
